# Generated by Django 6.1 on 2026-08-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_codingsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingsession',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
