# Generated by Django 6.1 on 2026-09-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_codingsession_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingsession',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
    ]
